name: EAS Update

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install EAS CLI
        run: npm install -g eas-cli

      - name: Run EAS Update
        run: eas update --branch preview --message "Auto OTA Update"
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
